CREATE TABLE user (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL
);

CREATE TABLE music (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(255) NOT NULL,
  jacket TEXT,
  artist VARCHAR(255) NOT NULL
);

CREATE TABLE favorites (
  user_id INT UNSIGNED NOT NULL,
  music_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (user_id, music_id),
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
  FOREIGN KEY (music_id) REFERENCES music(id) ON DELETE CASCADE
);
